<?php
/**
 * vos.21ces.com 의 Q&A / Notice / FAQ / Free Board 정확한 설정값 (skin_config 포함).
 * 호스팅 dist 의 install-core.php Step 4 가 이 시드 기반으로 board INSERT.
 * 사장님 dev 환경의 게시판 = 다국어 사용자가 보면서 스킨 활용법 익히는 매뉴얼 데모.
 */

return array (
  0 => 
  array (
    'slug' => 'notice',
    'title' => 'Notice',
    'category' => 'notice',
    'robots_tag' => 'all',
    'skin' => 'default',
    'layout' => 'default',
    'per_page' => 20,
    'search_per_page' => 20,
    'page_count' => 10,
    'list_columns' => '["no","title","nick_name","created_at","view_count"]',
    'sort_field' => 'created_at',
    'sort_direction' => 'DESC',
    'except_notice' => 1,
    'show_category' => 0,
    'allow_comment' => 1,
    'use_anonymous' => 0,
    'anonymous_name' => 'anonymous',
    'allow_secret' => 0,
    'consultation' => 0,
    'use_trash' => 1,
    'update_order_on_comment' => 1,
    'comment_length_limit' => 128,
    'protect_content_by_comment' => 0,
    'protect_by_days' => 0,
    'doc_length_limit' => 0,
    'perm_list' => 'all',
    'perm_read' => 'all',
    'perm_write' => 'admin',
    'perm_comment' => 'member',
    'perm_manage' => 'admin',
    'is_active' => 1,
  ),
  1 => 
  array (
    'slug' => 'qna',
    'title' => 'Q&A',
    'category' => 'qna',
    'robots_tag' => 'all',
    'skin' => 'qna',
    'skin_config' => '{"show_title":"1","title_text":"Q&A","subtitle_text":"질문과 답변","title_bg_type":"none","title_bg_image":"","title_bg_video":"","title_bg_height":"280","title_bg_overlay":"40","primary_color":"#22c55e","posts_per_page":"10","show_no_answer_badge":"1","expand_first":"1","content_width":"max-w-5xl"}',
    'layout' => 'modern-copy-260413',
    'per_page' => 20,
    'search_per_page' => 20,
    'page_count' => 10,
    'list_columns' => '["no","title","nick_name","created_at","view_count"]',
    'sort_field' => 'created_at',
    'sort_direction' => 'desc',
    'except_notice' => 1,
    'show_category' => 0,
    'allow_comment' => 1,
    'use_anonymous' => 0,
    'anonymous_name' => 'anonymous',
    'allow_secret' => 0,
    'consultation' => 0,
    'use_trash' => 1,
    'update_order_on_comment' => 1,
    'comment_length_limit' => 128,
    'protect_content_by_comment' => 0,
    'protect_by_days' => 0,
    'doc_length_limit' => 0,
    'perm_list' => 'all',
    'perm_read' => 'all',
    'perm_write' => 'member',
    'perm_comment' => 'member',
    'perm_manage' => 'admin',
    'is_active' => 1,
  ),
  2 => 
  array (
    'slug' => 'faq',
    'title' => 'FAQ',
    'category' => 'faq',
    'robots_tag' => 'all',
    'skin' => 'faq',
    'skin_config' => '{"primary_color":"#22c55e","posts_per_page":10,"show_category_filter":true,"expand_first":false}',
    'layout' => 'default',
    'per_page' => 10,
    'search_per_page' => 20,
    'page_count' => 10,
    'list_columns' => '["no","title","nick_name","created_at","view_count"]',
    'sort_field' => 'created_at',
    'sort_direction' => 'DESC',
    'except_notice' => 1,
    'show_category' => 0,
    'allow_comment' => 1,
    'use_anonymous' => 0,
    'anonymous_name' => 'anonymous',
    'allow_secret' => 0,
    'consultation' => 0,
    'use_trash' => 1,
    'update_order_on_comment' => 1,
    'comment_length_limit' => 128,
    'protect_content_by_comment' => 0,
    'protect_by_days' => 0,
    'doc_length_limit' => 0,
    'perm_list' => 'all',
    'perm_read' => 'all',
    'perm_write' => 'admin',
    'perm_comment' => 'member',
    'perm_manage' => 'admin',
    'is_active' => 1,
  ),
  3 => 
  array (
    'slug' => 'free',
    'title' => 'Free Board',
    'category' => 'board',
    'robots_tag' => 'all',
    'skin' => 'default',
    'skin_config' => '{"use_wizard":"admin","font_awesome":"internal","list_style":"table","allow_style_switch":"1","posts_per_row":"5","use_link_board":"none","link_target":"_blank","primary_color":"#3b82f6","border_radius":"rounded","title_bg_type":"none","title_bg_image":"","title_bg_video":"","title_bg_height":"200","title_bg_overlay":"40","title_text_color":"auto","custom_css":"","custom_html_header":"","custom_html_footer":"","show_category":"0"}',
    'layout' => 'default',
    'per_page' => 20,
    'search_per_page' => 20,
    'page_count' => 10,
    'list_columns' => '["no","title","nick_name","created_at","view_count"]',
    'sort_field' => 'created_at',
    'sort_direction' => 'DESC',
    'except_notice' => 1,
    'show_category' => 0,
    'allow_comment' => 1,
    'use_anonymous' => 0,
    'anonymous_name' => 'anonymous',
    'allow_secret' => 0,
    'consultation' => 0,
    'use_trash' => 1,
    'update_order_on_comment' => 1,
    'comment_length_limit' => 128,
    'protect_content_by_comment' => 0,
    'protect_by_days' => 0,
    'doc_length_limit' => 0,
    'perm_list' => 'all',
    'perm_read' => 'all',
    'perm_write' => 'member',
    'perm_comment' => 'member',
    'perm_manage' => 'admin',
    'is_active' => 1,
  ),
);
