-- 017: 게시판 시스템 테이블 생성

CREATE TABLE IF NOT EXISTS `rzx_boards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(50) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `category` VARCHAR(50) DEFAULT 'board',
  `description` TEXT DEFAULT NULL,
  `seo_keywords` VARCHAR(500) DEFAULT '',
  `seo_description` VARCHAR(500) DEFAULT '',
  `robots_tag` VARCHAR(10) DEFAULT 'all',
  `skin` VARCHAR(50) DEFAULT 'default',
  `per_page` INT DEFAULT 20,
  `search_per_page` INT DEFAULT 20,
  `page_count` INT DEFAULT 10,
  `header_content` TEXT DEFAULT NULL,
  `footer_content` TEXT DEFAULT NULL,
  `list_columns` JSON DEFAULT NULL,
  `sort_field` VARCHAR(30) DEFAULT 'created_at',
  `sort_direction` VARCHAR(4) DEFAULT 'DESC',
  `except_notice` TINYINT(1) DEFAULT 1,
  `show_category` TINYINT(1) DEFAULT 0,
  `allow_comment` TINYINT(1) DEFAULT 1,
  `use_anonymous` TINYINT(1) DEFAULT 0,
  `anonymous_name` VARCHAR(50) DEFAULT 'anonymous',
  `allow_secret` TINYINT(1) DEFAULT 0,
  `consultation` TINYINT(1) DEFAULT 0,
  `use_trash` TINYINT(1) DEFAULT 1,
  `update_order_on_comment` TINYINT(1) DEFAULT 0,
  `comment_delete_message` VARCHAR(20) DEFAULT 'no',
  `doc_length_limit` INT DEFAULT 1024,
  `comment_length_limit` INT DEFAULT 128,
  `protect_content_by_comment` TINYINT(1) DEFAULT 0,
  `protect_by_days` INT DEFAULT 0,
  `admin_mail` VARCHAR(200) DEFAULT '',
  `perm_list` VARCHAR(20) DEFAULT 'all',
  `perm_read` VARCHAR(20) DEFAULT 'all',
  `perm_write` VARCHAR(20) DEFAULT 'member',
  `perm_comment` VARCHAR(20) DEFAULT 'member',
  `perm_manage` VARCHAR(20) DEFAULT 'admin',
  `is_active` TINYINT(1) DEFAULT 1,
  `sort_order` INT DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rzx_board_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `board_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(50) DEFAULT NULL,
  `color` VARCHAR(7) DEFAULT '',
  `sort_order` INT DEFAULT 0,
  `is_active` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_board_id` (`board_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rzx_board_posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `board_id` INT NOT NULL,
  `category_id` INT DEFAULT NULL,
  `user_id` INT DEFAULT NULL,
  `title` VARCHAR(300) NOT NULL,
  `content` LONGTEXT DEFAULT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  `is_notice` TINYINT(1) DEFAULT 0,
  `is_secret` TINYINT(1) DEFAULT 0,
  `is_anonymous` TINYINT(1) DEFAULT 0,
  `nick_name` VARCHAR(100) DEFAULT '',
  `view_count` INT DEFAULT 0,
  `comment_count` INT DEFAULT 0,
  `like_count` INT DEFAULT 0,
  `dislike_count` INT NOT NULL DEFAULT 0,
  `file_count` INT DEFAULT 0,
  `list_order` BIGINT DEFAULT 0,
  `update_order` BIGINT DEFAULT 0,
  `status` ENUM('published','draft','trash') DEFAULT 'published',
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_board` (`board_id`),
  KEY `idx_category` (`category_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_list_order` (`board_id`,`list_order`),
  KEY `idx_status` (`board_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rzx_board_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `board_id` INT NOT NULL,
  `user_id` INT DEFAULT NULL,
  `parent_id` INT DEFAULT NULL,
  `depth` TINYINT DEFAULT 0,
  `content` TEXT NOT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  `is_secret` TINYINT(1) DEFAULT 0,
  `is_anonymous` TINYINT(1) DEFAULT 0,
  `nick_name` VARCHAR(100) DEFAULT '',
  `like_count` INT DEFAULT 0,
  `status` ENUM('published','deleted','trash') DEFAULT 'published',
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_post` (`post_id`),
  KEY `idx_board` (`board_id`),
  KEY `idx_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rzx_board_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `board_id` INT NOT NULL,
  `original_name` VARCHAR(300) NOT NULL,
  `stored_name` VARCHAR(300) NOT NULL,
  `file_path` VARCHAR(500) NOT NULL,
  `file_size` INT DEFAULT 0,
  `mime_type` VARCHAR(100) DEFAULT '',
  `download_count` INT DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_post` (`post_id`),
  KEY `idx_board` (`board_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rzx_board_votes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `user_id` INT DEFAULT NULL,
  `ip_address` VARCHAR(45) NOT NULL DEFAULT '',
  `vote_type` ENUM('like','dislike') NOT NULL DEFAULT 'like',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_user_vote` (`post_id`,`user_id`,`vote_type`),
  KEY `idx_post` (`post_id`),
  KEY `idx_ip` (`post_id`,`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
